# Generated by Django 4.1.1 on 2022-10-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_userprofile_portfolio_userprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
